# Generated by Django 5.0.1 on 2024-02-21 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=12)),
                ('type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('boolean', 'boolean'), ('date', 'date'), ('time', 'time'), ('datetime', 'datetime'), ('float', 'float'), ('image', 'image'), ('file', 'file')], default='string', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('default', models.TextField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='path/')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.category')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=4)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.country')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('contact_number', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='published', max_length=30)),
                ('photo', models.ImageField(upload_to='path/')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_top', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalFieldThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='path/')),
                ('file', models.FileField(blank=True, null=True, upload_to='path/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.job')),
                ('optional_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.optionalfield')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='optional_field',
            field=models.ManyToManyField(through='ads.OptionalFieldThrough', to='ads.optionalfield'),
        ),
    ]
