# Generated by Django 5.0.1 on 2024-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_category_icon_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='optional_field',
            field=models.ManyToManyField(blank=True, null=True, through='ads.OptionalFieldThrough', to='ads.optionalfield'),
        ),
    ]
