# Generated by Django 5.0.1 on 2024-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_auth_uid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Social UID'),
        ),
    ]
